[[shades]]
name = "vibrance"
default = true  # shader to use during times when there is no other shader scheduled

[[shaders]]
name = "blue-light-filter"
start_time = 23:00:00
end_time = 06:00:00   # optional if you have more than one shade with start_time
[shaders.config]
temperature = 5000.0  # 1000.0 - 40000.0
strength = 1.0        # 0.0 - 1.0
