return {
  "mistweaverco/kulala.nvim",
  keys = {
    { "<leader>k", "", desc = "+Kuala", mode = { "n", "v" } },
    { "<leader>kb", function() require("kulala").scratchpad() end, desc = "Open scratchpad" },
    { "<leader>ko", function() require("kulala").open() end, desc = "Open kulala" },
    {
      "<leader>kt",
      function() require("kulala").toggle_view() end,
      ft = { "http", "rest" },
      desc = "Toggle headers/body",
    },
    { "<leader>kS", function() require("kulala").show_stats() end, ft = { "http", "rest" }, desc = "Show stats" },
    { "<leader>kq", function() require("kulala").close() end, ft = { "http", "rest" }, desc = "Close window" },
    { "<leader>kc", function() require("kulala").copy() end, ft = { "http", "rest" }, desc = "Copy as cURL" },
    { "<leader>kC", function() require("kulala").from_curl() end, ft = { "http", "rest" }, desc = "Paste from curl" },
    { "<leader>ks", function() require("kulala").run() end, mode = { "n", "v" }, desc = "Send request" },
    {
      "<CR>",
      function() require("kulala").run() end,
      mode = { "n", "v" },
      ft = { "http", "rest" },
      desc = "Send request <cr>",
    },
    { "<leader>ka", function() require("kulala").run_all() end, mode = { "n", "v" }, desc = "Send all requests" },
    {
      "<leader>ki",
      function() require("kulala").inspect() end,
      ft = { "http", "rest" },
      desc = "Inspect current request",
    },
    { "<leader>kr", function() require("kulala").replay() end, desc = "Replay the last request" },
    { "<leader>kf", function() require("kulala").search() end, ft = { "http", "rest" }, desc = "Find request" },
    {
      "<leader>kn",
      function() require("kulala").jump_next() end,
      ft = { "http", "rest" },
      desc = "Jump to next request",
    },
    {
      "<leader>kp",
      function() require("kulala").jump_prev() end,
      ft = { "http", "rest" },
      desc = "Jump to previous request",
    },
    {
      "<leader>ke",
      function() require("kulala").set_selected_env() end,
      ft = { "http", "rest" },
      desc = "Select environment",
    },
    {
      "<leader>ku",
      function() require("lua.kulala.ui.auth_manager").open_auth_config() end,
      ft = { "http", "rest" },
      desc = "Manage Auth Config",
    },
    {
      "<leader>kg",
      function() require("kulala").download_graphql_schema() end,
      ft = { "http", "rest" },
      desc = "Download GraphQL schema",
    },
    {
      "<leader>kx",
      function() require("kulala").scripts_clear_global() end,
      ft = { "http", "rest" },
      desc = "Clear globals",
    },
    {
      "<leader>kX",
      function() require("kulala").clear_cached_files() end,
      ft = { "http", "rest" },
      desc = "Clear cached files",
    },
  },
  opts = {
    global_keymaps = false,
    kulala_keymaps_prefix = "",
  },
}
