
[[Snippets]]
  Description = "regenerate efi"
  Filename = "/home/arch/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "sudo efibootmgr -c -d /dev/sda -p 1 -L \"EFISTUB ARCH\" -l \"\\EFI\\Linux\\arch-linux.efi\" -u \"root=UUID=1777cdda-a9d6-46ab-8226-deaa79b62b1a rw rootflags=subvol=@ loglevel=3 quiet nvidia_drm.modeset=1 nvidia_drm.fbdev=1 nvidia.NVreg_PreserveVideoMemoryAllocations=1\" "

[[Snippets]]
  Description = "delete efi entry"
  Filename = "/home/arch/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "sudo efibootmgr -B -b 0000"

[[Snippets]]
  Description = "mount ntfs"
  Filename = "/home/arch/.config/pet/snippet.toml"
  Output = ""
  Tag = []
  command = "sudo mount /dev/sdb2 /mnt/hardDrive"
